### ISSUE TITLE
The burn function makes this not EIP-5114 compatible.

### ISSUE THREAD

**Issue by MicahZoltu** [TeamSHARKZ/soulbound#1]
https://github.com/TeamSHARKZ/soulbound/blob/191c3734b1a295a215e67fd856d2e5433d498e44/contracts/lib/5114/ERC5114SoulBadge.sol#L187-L219

EIP-5114 requires that once a badge is attached to an owner, it will permanently be attached to that owner and third parties can cache the result indefinitely.  This is similar to IPFS, where once you have the file a hash points to, you can infinitely cache that result and you never need to query for it again.

The burn function makes it so that a badge *may* go from existing to non-existant, which means you can no longer cache the result infinitely, thus breaking EIP-5114 compatibility.

**Comment by jasonhoi** [comment]
Thanks for your review and comment, we now removed all burning function from https://github.com/TeamSHARKZ/soulbound/blob/main/contracts/lib/5114/ERC5114SoulBadge.sol and IERC5114 interface file.
